### ISSUE TITLE
How do I access track data?

### ISSUE THREAD

**Issue by fdoyon** [mozilla/mp4parse-rust#133]
Hello, I am using this crate to read an mp4 container that contains audio tracks I need to decode, I am not sure how to get access to the audio packets of each individual track.

So far I can access the `SampleEntry::Audio` of each track but in order to decode the packets, I need to be able to calculate the offset each packet in the container file, which eludes me at the moment.

Thank you.

**Comment by rillian** [comment]
Unfortunately this is not currently possible with just the Rust api in the `mp4parse crate`. You can do with the `Mp4Parse::sample_table_mut()` method from the `mp4parse_capi` crate.

It would be good to port that logic over, but our use in Firefox involves constructing `#[repr(C)]` structs we can pass to C++ code, so that's where we implemented it first.

**Comment by alfredoyang** [comment]
Maybe we should move ```Mp4Parse::sample_table_mut``` to ```mp4parse crate``` and try to thin ```mp4parse_capi``` as much as possible.

**Comment by palad1** [comment]
Thanks for the pointer, I was not sure what the use-case for ther `mp4parse_capi` crate and assumed it was only a thin C wrapper around `mp4parse` but it seems there's extra functionality which I should use.
