### ISSUE TITLE
read_mp4 can expose uninitialised data to third party code (unsound)

### ISSUE THREAD

**Issue by nox** [mozilla/mp4parse-rust#172]
[`read_mp4`](https://github.com/mozilla/mp4parse-rust/blob/26e614bbcb4d7322dc2e4b7e15391bdb30b9f7be/mp4parse/src/lib.rs#L700) calls [`read_moov`](https://github.com/mozilla/mp4parse-rust/blob/26e614bbcb4d7322dc2e4b7e15391bdb30b9f7be/mp4parse/src/lib.rs#L729) which calls [`read_pssh`](https://github.com/mozilla/mp4parse-rust/blob/26e614bbcb4d7322dc2e4b7e15391bdb30b9f7be/mp4parse/src/lib.rs#L783) which calls [`read_buf`](https://github.com/mozilla/mp4parse-rust/blob/26e614bbcb4d7322dc2e4b7e15391bdb30b9f7be/mp4parse/src/lib.rs#L796) which calls [`allocate_read_buf`](https://github.com/mozilla/mp4parse-rust/blob/26e614bbcb4d7322dc2e4b7e15391bdb30b9f7be/mp4parse/src/lib.rs#L2320) and passes its result to [`Read::read`](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read).

https://github.com/mozilla/mp4parse-rust/blob/26e614bbcb4d7322dc2e4b7e15391bdb30b9f7be/mp4parse/src/lib.rs#L2320-L2321

But the trait `Read` is not unsafe, and it is never guaranteed to limit itself to *writing* to its single argument `buf`, and the result of `allocate_read_buf` is a vector of uninitialised bytes (that function should be unsafe, btw).

There were discussions about introducing a new unsafe trait in libstd to signal that a `Read` implementation doesn't read in the writer it's supposed to write to, I don't know what became of it but I just found out about https://github.com/rust-lang/rust/issues/42788 which seems related.

**Comment by kinetiknz** [comment]
Thanks for filing this.  I wasn't aware of that pitfall for Read, but now that I've re-read the trait's documentation I understand this can happen.

In this particular case:
- Only the "mp4parse_fallible" path of allocate_read_buf can return an uninitialized vec.
- The "mp4parse_fallible" feature is only safe to enable within Gecko due to guaranteed allocator sharing between subsystems.
- Gecko only ever passes in a Read implementation that does not read from the buffer passed in to Read::read.

So this problem can't happen in practice in this code.

However, it's easy to address by initializing the buffer in the "mp4parse_fallible" path and seems worth doing since otherwise allocate_read_buf should be marked unsafe as you mentioned.
