### ISSUE TITLE
Put the capi module behind a feature flag

### ISSUE THREAD

**Issue by nox** [mozilla/mp4parse-rust#18]
Servo doesn't need the capi module, and this brings rusty-cheddar and syntex to our already quite big dependency graph. Could that thing be put behind a feature flag?

**Comment by rillian** [comment]
I don't object in principle. We've also wanted that because it slows down testing so much. However, there doesn't seem to be any way to feature-ize `build.rs` or code in `tests/` and `examples/` so this involves a lot of tedious `#[cfg(...)]` markup.

https://github.com/rillian/mp4parse-rust/commit/4d67e0155ca14b4b78d62642ebff44e55c4b9dbd

It's also going to complicate the travis config. AFAICT we'll have to move to an external build script to conditionalize the C++ test. Let me know if you come up with something better.

**Comment by nox** [comment]
We can just split the crates (but keep everything in a single repos) into mp4parse and mp4parse_capi. Would you be ok with that?

**Comment by rillian** [comment]
Yes, I think that's probably the right approach. Thanks for doing the patch.
