### ISSUE TITLE
rfc: using mp4parse for mp4demuxer

### ISSUE THREAD

**Issue by npajkovsky** [mozilla/mp4parse-rust#214]
Hello,

I'm about the write video packager and I'd like to use mp4parse as
base for parsing mp4 container. The reading part is pretty good, but
there's some parts which needs tweaks. And before I will send any
patches, I'd like to discussed them.

1) Not all boxes are accessible after reading

```
pub fn read_mp4
    while let Some(mut b) = iter.next_box()? {
        match b.head.name {
            BoxType::FileTypeBox => {
                let ftyp = read_ftyp(&mut b)?;
                found_ftyp = true;
                debug!("{:?}", ftyp);

		^^^ at this point freed and not accesable
```

in my PoC, I have extended internal data `MediaContext` and store box
there. But there are more of them.

2) fullbox's `version` and `flags` and not accessible as well

```
read_mdhd
   let (version, _) = read_fullbox_extra(src)?;


    Ok(MediaHeaderBox {
        timescale,
        duration,
    })
```

so when you want to implement write_mdhd(), you cannot do that without
`version`.

There's multiple options to fix this.

  a) extend MediaHeaderBox struct with new member `version` or `flags`
  (depends on box)
  b) create new struct FullBoxHeader

```
   #[derive(Debug, Default)]
   pub struct FullBoxHeader {
       pub version: u8,
       pub flags: u32,
   }
```

and either return it along with parsed box, e.g.

```
    Ok(MediaHeaderBox {
        timescale,
        duration,
    }, fullbox_header)
```

or add new member into struct.

3) some bytes are skipped
Some of bytes are skipped for good reasons, but some of them will trim
output after writing box.

```
fn read_video_sample_entry
    // Skip uninteresting fields.
    skip(src, 50)?;

    // Skip clap/pasp/etc. for now.
```

4) low hanging fruits, are struct, that are not accessible outside of this module

Please let me know, if any of above changes will work for you.

-- 
Nikola

**Comment by kornelski** [comment]
In general I've found that this crate is not usable for parsing data that doesn't have a dedicated `read_something` function.

I think it'd be very useful to expose "SAX-like" API (visitor pattern) that allows caller to visit every box. 

When parsing a box, call a user callback with that box's information. The callback could even control whether to recurse into sub-boxes or skip them.

This way users could implement their own arbitrary data extraction, nearly zero-copy, without a need for specific parser functions.

```rust
pub trait Visitor {
   fn visit_ftyp(&self, ftyp: &FileTypeBox) -> AbortOrContinue;
   fn visit_mdat(&self, mdat: &MediaDataBox) -> AbortOrContinue;
   fn visit_etc(&self, etc: &AndSomeOtherBoxes) {}
}
```

This would also make it a *streaming* API, so that clients could work with partially loaded files. Currently for example, `read_avif` won't expose any image metadata before the entire file is downloaded.
