### ISSUE TITLE
TryBox is unsound

### ISSUE THREAD

**Issue by kornelski** [mozilla/mp4parse-rust#221]
`TryBox` assumes that `Box::drop` will use `libc::free` to deallocate memory. This is not true if a crate uses jemallocator, or any custom allocator.

This could be fixed with:

1. Not using `Box` for `inner`, but keeping the raw pointer, and implementing `Drop` for `TryBox` that calls `libc::free`

2. or using std allocator API to use the same allocator as `Box`

I think option 1 is the simplest and makes least assumptions about Rust inner workings.

There's a more theoretical issue of `TryBox` not checking alignment. `malloc` gives alignment for largest platform-native type, but Rust types might ask for bigger alignment. An `assert` would suffice for this implementation.

`std::mem::forget(std::mem::replace` can be simplified to `ptr::write`.

**Comment by baumanj** [comment]
Thanks for catching this. Would you agree that switching to [the `fallible_collections` version of `TryBox`](https://github.com/vcombey/fallible_collections/blob/f30aee9711d1d3edbfd222bef8d210cd0d821a7f/src/boxed.rs) would resolve this since it uses the stdlib allocator API to provide fallible allocation?

**Comment by kornelski** [comment]
Yes, that looks good.
