### ISSUE TITLE
Chunking/splitting  a video file. 

### ISSUE THREAD

**Issue by osain-az** [mozilla/mp4parse-rust#372]
Hi. 
This is not actually an issue  but more of a question. 

I am trying to chunk a video file given any offset. 
Is it possible  to chunk/split  a video.pm4 file ? . For example, chunk by a given offset .
I have looked at the documentation but have not really seen any method for that. 

Can you point to the method or other suggestions to chunking/spitting  a video file.

**Comment by kinetiknz** [comment]
There's no support for doing so in mp4parse-rust (it's only a reader, no support for (re)writing MP4), but it is possible to split MP4 files by (approximate) byte or time offset in a couple of ways depending on your needs.  Most likely, you'll want to create a "fragmented MP4".  I recommend investigating ffmpeg or Bento4, as they both offer options to achieve this.

I'll close this since there's nothing actionable for mp4parse-rust.

**Comment by osain-az** [comment]
> There's no support for doing so in mp4parse-rust (it's only a reader, no support for (re)writing MP4), but it is possible to split MP4 files by (approximate) byte or time offset in a couple of ways depending on your needs. Most likely, you'll want to create a "fragmented MP4". I recommend investigating ffmpeg or Bento4, as they both offer options to achieve this.
> 
> I'll close this since there's nothing actionable for mp4parse-rust.

Thanks for the tips
