### ISSUE TITLE
Recommendations for streaming?

### ISSUE THREAD

**Issue by MarkSwanson** [mozilla/mp4parse-rust#41]
I'm thinking about creating a streaming buffer that implements Read, and uses something like fringe or context to suspend mp4parse until more data is available.

The data is coming in asynchronously from a web server and I have to stream chunks into mp4parse-rust (I can not save all of the chunks to disk and pass the complete file to mp4parse).

Any other suggestions? 
I was hoping someone could point me to something similar...

Thanks!

**Comment by baumanj** [comment]
Modifying this code to support async rust or streaming is something I think we may look into in the future, but not in the short term. For general resources about these topics, I'd recommend https://areweasyncyet.rs/ and https://users.rust-lang.org/.

I'm closing this now since it's not an actionable issue for this codebase.
